### PR TITLE
Feature/al 174 opt in service wrapping

### PR DESCRIPTION
**Pull request by Crisfole**
Two things to review:

 1. Rubocop and pre-push changes.(commits bb27a9d to 2ed93d0)
 2. Opt-in to service wrapping (c47c435 to 2866051)

### CODE REVIEW

**Comment by egreer** [comment]
Can you reorganize the renamed commands in rubocop.yml so that the file remains in alphabetical order for easier lookups?

Also git hooks don't install on windows for the host (when installed from the guest) so I'll have to look into fixing that.

**Comment by egreer** [comment]
Never mind about the reorganizing, forgot this project hasn't yet been organized. 

Changes look fine to me

**Comment by Crisfole** [comment]
@egreer @wkirby Please review.

**Comment by egreer** [comment]
Looks fine to me

**Pull request merged**
