### PR TITLE
Target ruby 2.1 instead of ruby 2.3

### PR DESCRIPTION
**Pull request by ncallaway**
We should support ruby 2.1, but right now we don't

### CODE REVIEW

**Comment by wkirby** [comment]
Is there a reason to target 2.1 instead of 2.3? Why not both?

**Comment by wkirby** [comment]
Oh. I see. I thought this was for travis not rubocop.

**Comment by ncallaway** [comment]
2.3 is backwards compatible with 2.1
2.1 is not forwards compatible with 2.3

So, if we use 2.3 features that are not available in 2.1, our code will break in a a 2.1 environment.

**Comment by ncallaway** [comment]
Oh, yea, that.

**Pull request merged**
